treebook/config/routes.rb
Treebook::Application.routes.draw do
  get "profiles/show"

  devise_for :users

  devise_scope :user do
    get "register", :to => "devise/registrations#new", as: :register
    get "login", :to => "devise/sessions#new", as: :login
    get "logout", :to => "devise/sessions#destroy", as: :logout
  end

  resources :statuses

  get "feed", :to => "statuses#index", as: :feed

  root :to => "statuses#index"

  get '/:id', to: 'profiles#show'
  

end

treebook/app/models/status.rb
class Status < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true,
  						length: { minimum: 2 }

  validates :user_id, presence: true
end

treebook/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  						:first_name, :last_name, :profile_name
  # attr_accessible :title, :body

  validates :first_name, presence: true

  validates :last_name, presence: true
  
  validates :profile_name, presence: true, 
                            uniqueness: true,
                            format: {
                              with: /^[a-zA-Z0-9_-]+$/,
                              message: 'Must be formated correctly.'
                            }

  has_many :statuses

  def full_name
  	first_name + " " + last_name 
  end

  def gravatar_url
    stripped_email = email.strip
    downcased_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcased_email)
    "http://gravatar.com/avatar/#{hash}"
  end

end

treebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

treebook/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show

  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@statuses = @user.statuses.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, format: [:html]
  	end
  	
  end
end

treebook/app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statuses }
    end
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
    @status = Status.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  # GET /statuses/new.json
  def new
    @status = Status.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @status }
    end
  end

  # GET /statuses/1/edit
  def edit
    @status = Status.find(params[:id])
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(params[:status])

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render json: @status, status: :created, location: @status }
      else
        format.html { render action: "new" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /statuses/1
  # PUT /statuses/1.json
  def update
    @status = Status.find(params[:id])

    respond_to do |format|
      if @status.update_attributes(params[:status])
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status = Status.find(params[:id])
    @status.destroy

    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end
end

treebook/app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class (type)
		case type
		when :alert
			"alert-error"
		when :notice
			"alert-success"
		end
	end
end

treebook/app/helpers/profiles_helper.rb
module ProfilesHelper
end

treebook/app/helpers/statuses_helper.rb
module StatusesHelper
end

treebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="#">Treebook</a>
			<ul class="nav">
				<li><%= link_to "All Statuses", feed_path %></li>
			</ul>
			<ul class="nav pull-right">
				<% if user_signed_in? %>			
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
					<li><%= link_to "Log Out", logout_path %></li>
				<% else %>			
					<li><%= link_to "Register", register_path  %></li>
					<li><%= link_to "Log In", login_path  %></li>
				<% end %></ul>
		</div>
	</div>
</div>

	<div class="container">

		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %>">
				<button type="button" class="close" data-dismiss="alert">×</button>
				<%= message %>
			</div>
		<% end %>

		<%= yield %>
		
	</div>

</body>
</html>

treebook/app/views/profiles/show.html.erb
<div class="page-header">
	<h1> <%= @user.full_name %> </h1>
</div>

<% if @statuses %>
	<% @statuses.each do |status| %>
		<div class="well">
			<%= status.content %>
			<hr />
			<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
		</div>
	<% end %>
<% end %>

treebook/app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: {class: "form-horizontal"}) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

treebook/app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

treebook/app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All of the Statuses</h1>
</div>

<%= link_to "Post a New Status", new_status_path, class: "btn btn-success" %>

<% @statuses.each do |status| %>

<div class="status">
<div class="row">
  <div class="span1">
    <%= image_tag status.user.gravatar_url %>
  </div>
  <div class="span7">
    <strong><%= status.user.profile_name %></strong> 

    <p><%= status.content %></p>
    <div class="meta">
      <%= link_to time_ago_in_words(status.created_at) + " ago", status %>
      <span class="admin">
        | <%= link_to "Edit", edit_status_path(status) %> 
        | <%= link_to "Delete", status, method: :delete, data: {confirm: "Are you sure you want to delete this status?"} %>
      </span>
    </div>

  </div>
</div>
</div>

<% end %>

treebook/app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

treebook/app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @status.user.full_name %>
</p>

<p>
  <b>Content:</b>
  <%= @status.content %>
</p>


<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>